### ISSUE TITLE
Home Assistant Sensor Config on Reboot

### ISSUE THREAD

**Issue by jacobkossman** [mplinuxgeek/ds2mqtt#3]
First of all, thank you for this script, very useful.

I'm just wondering if there's a way to get the sensor config pushed up regularly?

The issue is when you reboot HA, it doesn't have the config info for the sensors since the script only sends that on start. This means I have to SSH in and restart the service so HA knows the config. Thanks!

**Comment by HildingL** [comment]
Hello. I have the same problem, Did you find any solution?
Best regards, Hilding.

**Comment by jacobkossman** [comment]
> Hello. I have the same problem, Did you find any solution? Best regards, Hilding.

I ended up making a script inside HA to handle this and ran it on boot with an automation:

```
alias: On Home Assistant Start, Reboot rPi Temp Sensor
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: shell_command.restart_pi_sensor
    data: {}
mode: single
```

```
shell_command:
  restart_pi_sensor: ssh -i /config/ssh/id_rsa -o 'StrictHostKeyChecking=no' USER@HOST_IP 'sudo systemctl restart ds2mqtt'
```

You'll have to make an ssh key for HA and there were some pain points i can't remember anymore. I've since switched entirely to zigbee devices for temp now though.
